### PR TITLE
Update add-configuration.md

### PR DESCRIPTION
**Pull request by magedevjosh**
## Description
Updating example to match attribute description.

## To-do list
- [x] If my change impacts other components, I have tested to make sure they don't break.
- [x] If my change impacts documentation, I have updated the documentation accordingly.
- [x] I have read the [CONTRIBUTING document](/.github/CONTRIBUTING.md).
- [x] This pull request is ready to merge.

### CODE REVIEW

**Review by bdenham — APPROVED** [review]
👍

**Comment by bdenham** [comment]
https://github.com/magento import code to magento-devdocs/pagebuilder-docs

**Comment by bdenham** [comment]
@magento import code to magento-devdocs/pagebuilder-docs

**Comment by m2-github-services** [comment]
@bdenham the branch with the code is successfully imported into the `magento-devdocs/pagebuilder-docs` repository. Branch name: `imported-magedevjosh-pagebuilder-docs-55`.

**Pull request closed without merging**
