### PR TITLE
Fix typo in Readme with Duplicate description

### PR DESCRIPTION
**Pull request by julienanquetil**
## How and where has this been tested?
 - **How this was tested:** 
 - **Browser(s) and OS(s) this was tested with:** 

## To-do list

- [ ] If my change impacts other components, I have tested to make sure they don't break.
- [ ] If my change impacts documentation, I have updated the documentation accordingly.
- [ ] I have read the [CONTRIBUTING document](/.github/CONTRIBUTING.md).

- [ ] This pull request is ready to merge.

### CODE REVIEW

**Comment by bdenham** [comment]
@magento import code to magento-devdocs/pagebuilder-docs

**Comment by m2-github-services** [comment]
@bdenham the branch with the code is successfully imported into the `magento-devdocs/pagebuilder-docs` repository. Branch name: `imported-julienanquetil-pagebuilder-docs-51`.

**Review by bdenham — APPROVED** [review]

**Comment by bdenham** [comment]
@magento import code to magento-devdocs/pagebuilder-docs

**Comment by m2-github-services** [comment]
@bdenham the branch with the code is successfully imported into the `magento-devdocs/pagebuilder-docs` repository. Branch name: `imported-julienanquetil-pagebuilder-docs-51`.

**Comment by dshevtsov** [comment]
The fix was delivered in 47df23d.

**Pull request closed without merging**
