### PR TITLE
Make examples consistent

### PR DESCRIPTION
**Pull request by shochdoerfer**
I made the following adjustments:
- Make sure the code examples match the expected output & that the matching variable names are used
- I had to change the request method from `GET` to `POST` to make it work with the latest Magento 2.4.4. Not sure if this worked before or if the code example was just wrong

### CODE REVIEW

**Review by bdenham — APPROVED** [review]
Thanks, @shochdoerfer! Sorry for the delay.

**Comment by bdenham** [comment]
https://github.com/magento import code to magento-devdocs/pagebuilder-docs

**Comment by bdenham** [comment]
@magento import code to magento-devdocs/pagebuilder-docs

**Comment by m2-github-services** [comment]
@bdenham the branch with the code is successfully imported into the `magento-devdocs/pagebuilder-docs` repository. Branch name: `imported-bitExpert-forks-pagebuilder-docs-54`.

**Pull request merged**
