### PR TITLE
Remove reference to acme_quote

### PR DESCRIPTION
**Pull request by RikvdHeijden**
This should be example-quote as in the rest of the documentation

### CODE REVIEW

**Review by bdenham — APPROVED** [review]
Great catch, @RikvdHeijden! Sorry I didn't see this PR until now. Thanks for the fix!

**Comment by RikvdHeijden** [comment]
@bdenham 
Thanks for approving this merge request. Though it seems that I cannot finalize the process myself. Is there an action I'm supposed to take here?

**Comment by bdenham** [comment]
That's weird. Do you need to sign something. Hold on. I need to look at this in a browser. The GitHub app I'm using right now for iOS is really not very informative.

**Comment by bdenham** [comment]
@RikvdHeijden, all good now. Thanks for correcting that!

**Pull request merged**
