### PR TITLE
Lowercase `troubleshooting.md`

### PR DESCRIPTION
**Pull request by sad270**
Fix the case, use lowercase `troubleshooting.md`
PR for the https://github.com/magento/devdocs repo is coming 😄 

## To-do list

- [X] If my change impacts other components, I have tested to make sure they don't break.
- [X] If my change impacts documentation, I have updated the documentation accordingly.
- [X] I have read the [CONTRIBUTING document](/.github/CONTRIBUTING.md).

- [X] This pull request is ready to merge.

### CODE REVIEW

**Comment by bdenham** [comment]
running tests

**Comment by bdenham** [comment]
@magento import pr to magento-devdocs/pagebuilder-docs

**Review by bdenham — APPROVED** [review]
Thanks, @sad270. You beat me to it.

**Comment by bdenham** [comment]
@magento import pr to magento-devdocs/pagebuilder-docs

**Comment by dshevtsov** [comment]
@magento import code to magento-devdocs/pagebuilder-docs

**Comment by sidolov** [comment]
@magento import code to magento-devdocs/pagebuilder-docs

**Comment by m2-github-services** [comment]
@sidolov the branch with the code is successfully imported into the `magento-devdocs/pagebuilder-docs` repository. Branch name: `imported-sad270-magento2-page-builder-docs-49`.

**Comment by dshevtsov** [comment]
The fix was delivered in 53494b9

**Pull request closed without merging**
